// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

using BingWall.Core.Implementations;
using BingWall.Core.Interfaces;

namespace BingWall.iOS
{
    public partial class TodaysBingViewController : UIViewController
    {
        BingRepository bingRepo = new BingRepository(String.Empty, String.Empty);

        public TodaysBingViewController(IntPtr handle)
            : base(handle)
        {
            bingWallImageDownloadBtn.TouchUpInside += GetWallpaper;
        }

        public async void GetWallpaper(object sender, EventArgs e)
        {
            object response = null;
            try
            {
                response = await bingRepo.GetBingHomepageBackground();
            }
            catch (Exception x)
            {
                Console.WriteLine(x.StackTrace);
            }
            Console.WriteLine("Downloading image" + response.ToString());
        }
    }
}
