// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BingWall.iOS
{
	public partial class WallpaperBackupViewController : UIViewController
	{
		public WallpaperBackupViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
